[server]
Workers = 5000 # 解析数据包协程数
Size = 10 # 滑动窗口大小(分钟)
Rank = 30 # 滑动窗口内的流量排名数
PacketChan = 500000 # 数据包通道大小
Interval = 2 # 缓存更新间隔(秒)，用于页面数据支撑
Eth = "em1" # 网卡名称
Port = 31415 # WEB监听端口


[notify]
Enable = false # 是否启用通知，true启用
ThresholdValue = 10 # 大流量告警阈值
ThresholdUnit = "GB" # 大流量告警单位，GB或MB
FrequencyThreshold = 10000 # 高频请求告警阈值
WhiteList = ["", ""] # 告警忽略白名单IP
Location = "IDC" # 流量镜像服务器位置

[wecom]
Enable = false # 是否启用企业微信通知，true启用
WebHook = "" # 企业微信机器人Webhook地址

[mail]
Enable = false # 是否启用邮件通知，true启用
SmtpHost = "" # SMTP服务器地址
SmtpPort = 25 # SMTP服务器端口
Username = "" # SMTP用户名
Password = "" # SMTP密码
To = "" # 收件人地址
From = "" # 发件人地址
Cc = [""] # 抄送人地址

[kafka]
Enable = false # 是否启用Kafka，true启用
Brokers = ["", "", ""] # brokers集群地址
Topic = "" # topic名称
Size = 500000 # Kafka消息队列大小

[log]
LogPath = "/var/log/go_flow.log" # 日志路径，为空将输出控制台
LogLevel = "debug" # 日志级别
MaxSize = 10 # 日志文件大小(MB)
Compress = true # 是否压缩日志文件
MaxAge = 7 # 日志文件保存天数
MaxBackups = 10 # 日志文件保留个数
Format = "json" # 日志格式，json或text